### ISSUE TITLE
New signing CA used by ARRL

### ISSUE THREAD

**Issue by bwarden** [hessu/aprsc#30] opened 2016-05-13 22:43 UTC
Having requested a new LOTW certificate from ARRL after changing my callsign, I've discovered that they've apparently changed their signing certificate. As a result, APRS2 servers reject my certificate as having a self-signed cert in the chain. For reference, I've attached ARRL's new certificates.
[LogbookoftheWorldProductionCA.txt](https://github.com/hessu/aprsc/files/264188/LogbookoftheWorldProductionCA.txt)

**Comment by hessu** [comment] 2016-06-28 20:56
Thanks. This is not a bug or issue with aprsc, certificates are not shipped in aprsc, so I'll close this ticket.

**Closed by hessu** 2016-06-28 20:56 UTC
