### ISSUE TITLE
Denied Packets (Issue #48 #82 #83)

### ISSUE THREAD

**Issue by na7q** [hessu/aprsc#84] opened 2024-02-15 03:22 UTC
I will continue to open tickets until this is fully discussed amongst users and resolved. There's a reason we don't see progress with much ham software, it's this constant shutting down of user input. 

As told previously, "send RF and IS simultaneously" to resolve the issue. This does NOT resolve the issue. This ESPECIALLY does not resolve the issue with VARA APRS. Which is the NEW HF method for reliable APRS. 

Even if we were to send to IS and RF, we still have an issue. That being the packet sent to IS would be different than RF.
As shown below is a packet that will not only have a time difference of 12-18 seconds. It will also have a preset tocall replaced by VARA. VARA allows APRS to be brought into 2024 as a weak signal digital mode by doing this. 

No, we can't blame VARA. We the users opted for this (for many valid reasons). Because it's not the almighty developers of APRS servers who get to decide how APRS works, or some outdated club or organization. Now you're gonna go on and complain about it not being "standard" to the decade old doc. This isn't 1998.

Adapt or die.

Example packet, they are one in the same, and were sent at the exact same time.
2024-02-14 18:36:51 PST: [WA7GMX-8](https://aprs.fi/?c=raw&limit=&call=WA7GMX-8)>APWW11,TCPIP*,qAC,T2SPAIN:=/6Oo{/ORw& sT
2024-02-14 18:37:04 PST: [WA7GMX-8](https://aprs.fi/?c=raw&limit=&call=WA7GMX-8)>APVARA,qAO,[KJ5FA-9](https://aprs.fi/?c=raw&limit=&call=KJ5FA-9):=/6Oo{/ORw& sT

**Comment by k4jh** [comment] 2024-02-15 03:47
> On Feb 14, 2024, at 22:22, Mike ***@***.***> wrote:
> 
> ﻿
> I will continue to open tickets until this is fully discussed amongst users and resolved.
> 

Have you considered the possibility that aprsc isn’t the right tool for you?

Two people explained to you why aprsc functions the way it does. The author requested to stop opening tickets over this and you ignore his reasoned response.

How do you think that looks?

-jav k4jh

**Comment by hessu** [comment] 2024-02-15 09:21
The original tocall of APWW11 getting replaced is another issue, which I would call a serious issue in the VARA implementation. It certainly should not create modified versions of original packets, as those break loop protection, duplicate packet filtering, and they also break the detection of the original APRS software, as well as Mic-E position packet encoding.

Maybe @ldeffenb the author of APRSIS32, and @wb2osz the author of the Dire Wolf modem, might want to say something here, too.

> Adapt or die.

In think that is not a very nice thing to say, but I hope you feel better now.

**Comment by hessu** [comment] 2024-02-15 09:30
And, to reiterate from the previous ticket: I'm not saying this absolutely can not be changed, but I'm saying this is not the right place for that discussion, as it's an APRS-IS behaviour thing, not an aprsc issue.

The discussion needs to happen on APRSSIG for example, where we can have Pete Loveall and others on the discussion. Otherwise we might (1) break a lot of things accidentally, or (2) have differing functionality depending on whether you land on an aprsc server or a javaprssrvr server.

**Comment by hessu** [comment] 2024-02-15 09:57
Duplicate of: #48 (most discussion there), #82 and #83 .

**Comment by hessu** [comment] 2024-02-15 23:34
I've raised this up on the APRSSIG, so let's continue the discussion there with a broader audience and more developers. https://lists.tapr.org/pipermail/aprssig_lists.tapr.org/2024-February/thread.html

Please do not reopen another duplicate, it does not help or do any good.

**Closed by hessu** 2024-02-15 23:34 UTC
Labels: duplicate, invalid
