### ISSUE TITLE
Denied Packets (Issue #48 #82)

### ISSUE THREAD

**Issue by na7q** [hessu/aprsc#83] opened 2024-02-11 23:21 UTC
I am opening this back up because once closed by the admin I cannot re-open. I truly believe it must remain open until something is resolved with it. Leaving this open helps others know of the issues, that they could be facing that are identical. As we have seen, I am not alone with this issue regarding false "loop" detection that disregards valid packets.

**Comment by PhirePhly** [comment] 2024-02-12 22:32
This behavior is still the as-designed behavior for the APRS-IS protocol. Your argument isn't with aprsc but with the design of APRS as a whole. This is not the place to argue your point.

**Comment by hessu** [comment] 2024-02-14 06:13
Like @PhirePhly explained, this is not a bug in aprsc, but rather a design decision, which was probably done by Pete Loveall in javaprssrvr, perhaps 20-30 years ago. If it needs changing, we need to investigate what would break, why was this decision made back then (there might be a good reason we don't know), and would Pete be ready change javaprssrvr behaviour.

I will close this again. Please do not reopen again - this is maybe the 5th ticket about this, and I don't want open bug tickets here to be used as documentation for APRS-IS design. Closed tickets can be browsed too.

Have the discussion on APRSSIG for example. Thank you!

**Closed by hessu** 2024-02-14 06:13 UTC

**Comment by na7q** [comment] 2024-02-15 03:13
This is not the design of APRS. This is an issue. Regardless what you say, it is a chosen issue that MUST be discussed and considered for alternative options.

**Comment by na7q** [comment] 2024-02-15 03:27
> This behavior is still the as-designed behavior for the APRS-IS protocol. Your argument isn't with aprsc but with the design of APRS as a whole. This is not the place to argue your point.

Considering it is coded within APRSC. It seems that's just no the case. Even if it is "APRS" that has decided this. That doesn't mean we ignore it.

**Comment by na7q** [comment] 2024-02-15 03:29
> Like @PhirePhly explained, this is not a bug in aprsc, but rather a design decision, which was probably done by Pete Loveall in javaprssrvr, perhaps 20-30 years ago. If it needs changing, we need to investigate what would break, why was this decision made back then (there might be a good reason we don't know), and would Pete be ready change javaprssrvr behaviour.
> 
> I will close this again. Please do not reopen again - this is maybe the 5th ticket about this, and I don't want open bug tickets here to be used as documentation for APRS-IS design. Closed tickets can be browsed too.
> 
> Have the discussion on APRSSIG for example. Thank you!

Okay, so then we are saying that APRSC as a server, that creates this issue is not part of the issue? One does not have to follow outdated APRS "designs". Complaining on a 1995 website where users don't monitor will do nothing. You can't make the OG's listen. They'll go on about how FT8 is ruining the hobby. Just as they will say APRS must follow decades old guidelines that make no sense.

**Comment by k4jh** [comment] 2024-02-15 17:53
> On Feb 14, 2024, at 22:13, Mike ***@***.***> wrote:
> 
> 
> This is not the design of APRS. This is an issue. Regardless what you say, it is a chosen issue that MUST be discussed and considered for alternative options.

It is indeed not the design of APRS. It is the design of APRS-IS.

If you think it must be discussed, the proper venue is the APRSSIG list, not this one dedicated to aprsc.

-jav

**Comment by hessu** [comment] 2024-02-15 23:35
I've raised this up on the APRSSIG, so let's continue the discussion there with a broader audience and more developers. https://lists.tapr.org/pipermail/aprssig_lists.tapr.org/2024-February/thread.html
